version: "3.8"

services:
  hackrx-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - HACKRX_API_TOKEN=${HACKRX_API_TOKEN}
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL database for production
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=hackrx
      - POSTGRES_USER=hackrx_user
      - POSTGRES_PASSWORD=hackrx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
