services:
  - type: web
    name: hackrx-query-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: HACKRX_API_TOKEN
        value: 018fbf34e584c6effc325d2b54ba468383140299330b71b644cb73775d410be5
